### ISSUE TITLE
[FEATURE] The possibilty to set 60 fps in recording

### ISSUE THREAD

**Issue by Tanked4** [anonfaded/FadCam#42] opened 2024-09-21 14:29 UTC
### Description
Title

### Priority
- [ ] Low
- [☑] Medium
- [ ] High

**Comment by anonfaded** [comment] 2024-09-21 15:25
Have you tried the beta version which has framerate selection feature?
Download from here: https://github.com/anonfaded/FadCam/releases/tag/v1.2.0-beta

**Comment by s0llvan** [comment] 2024-11-20 12:14
Duplicate of #23

**Closed** 2024-11-21 13:58 UTC
Labels: enhancement, help wanted, good first issue
